In [51]:
import os as os
import pandas as pd
import numpy as np

In [52]:
df1 = pd.read_csv("unprocessed_Trec05_email")
df2 = pd.read_csv("unprocessed_Trec06_email")
df3 = pd.read_csv("unprocessed_Trec07_email")

In [53]:
print(df1.shape[0])
df1.head()

38267

                                               Email  Label
0  User ID:  enrondlr\nPW:        bnaweb22\n\n\n ...      1
1  \nHi Chris,  \n\nTonight we are rolling out a ...      1
2  Rika r these new?\n\n -----Original Message---...      1
3  John/Gerald,\n\nWe are currently trading under...      1
4  Gerald and Stacy -\n\nAttached is a worksheet ...      1

In [54]:
print(df2.shape[0])
print(df2["Email"][61554-38267])
df2.head()

31961
We Do What Viagra Can't<html><head><title></title></head><body bgcolor=#FFFFFF text=#000000><p>BLUE STEEL, a doctor approved, all-natural, 100% safe and effective sexual performance accelorator. Our GMP certified, scientifically formulated product contains the trademarked ingredient, Cernitin.</p><p>Cernitin alone has been shown to increase, prolong and intensify the number of orgasmic contractions of men suffering from erectile dysfunction or premature ejaculation!</p><p><br> BLUE STEEL is not a synthetic drug. It is a proprietary blended, natural supplement consisting of the highest quality ingredients. Even with natural ingredients, however, dosages and concentration levels are important for maintaining effectiveness and safety.</p><p>please visit our web site <a href=XXXX://www.accentedcx.com/as/>click here</a></p><p><a href=XXXX://www.accentedcx.com/e.html>Remove mail</a></p></body></html>

<html>
<br>
CONFIDENTIALITY CAUTION: If you have received this communication in error, please note that it is intended for the addressee only, is private and confidential and dissemination or copying prohibited. Please notify us immediately by e-mail and return the original message. We cannot assure that the integrity of this communication has been maintained nor that it is free of errors, virus, interception or interference. Thank you</html>

                                               Email  Label
0  The mailing list I queried about a few weeks a...      1
1             \n                                 ...      0
2  Academic Qualifications available from prestig...      0
3  Greetings all.  This is to verify your subscri...      1
4  try chauncey may conferred the luscious not co...      0

In [55]:
print(df3.shape[0])
df3.head()

61350

                                               Email  Label
0  <html>\n<body bgcolor="#ffffff">\n<div style="...      0
1  Hi, i've just updated from the gulus and I che...      1
2  Mega  authenticV I A G R A   $ DISCOUNT priceC...      0
3  \nHey Billy, \n\nit was really fun going out t...      0
4  \nsystem" of the home.  It will have the capab...      0

In [56]:
print(df1["Email"][0])
# We would need to remove escape sequence
# Lower casing
# Do other stuff from this link :https://www.kaggle.com/code/sudalairajkumar/getting-started-with-text-preprocessing

User ID:  enrondlr
PW:        bnaweb22


 -----Original Message-----
From: 	"BNA Highlights" <bhighlig@bna.com>
Sent:	Thursday, June 28, 2001 11:10 PM
To:	BNA Highlights
Subject:	June 29 -- BNA, Inc. Daily Labor Report

______________________________

DAILY LABOR REPORT
Highlights & Table of Contents
June 29, 2001
______________________________

ISSN 1522-5968

Registered Web subscribers can access the full text of these
articles by using the URL link supplied.

Information about becoming a subscriber or signing up for a
FREE Web trial is available at http://web.bna.com or call
BNA Customer Relations at 1-800-372-1033, Mon. - Fri. 8:30
am - 7:00 pm (ET).
__________

HIGHLIGHTS
__________


D.C. CIRCUIT OVERTURNS NLRB DECISION ON WORKPLACE CONDUCT
POLICIES

A California firm's two workplace policies barring abusive
and threatening language and restricting solicitation and
distribution did not constitute unfair labor practices, the
District of Columbia Circuit rules, overturning a National
Labor Relations Board decision ("Adtranz ABB Daimler-Benz
Transp. N.A. Inc. v. NLRB, "D.C. Cir., No. 00-1282,
6/26/01). The board held the workplace conduct policies of
Adtranz ABB Daimler-Benz Transportation N.A. Inc. interfered
with employees' exercise of their rights under the National
Labor Relations Act. The board ordered that a second
election be held to determine whether Adtranz employees in
Pittsburg, Calif., wanted to be represented by the
Machinists Automotive Trade District Lodge 190 of Northern
California.

The appeals court finds it lacks jurisdiction to consider
Adtranz's appeal of the order for a new election, because it
is not a final order. The court rejects the board's view
that the ban on abusive and threatening language was an
unfair labor practice regardless of whether it actually
chilled employees' exercise of their rights. Judge Sentelle
finds the solicitation-distribution rule is legal because it
"only applies to conduct during working time and in the work
place" and "applies across the board, so it cannot be said
to discriminate against unionization efforts or other
protected activity." . . . Page AA-1,  Text E-1

http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5k3h4_

http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5e3e4_


WORKPLACE PANIC ATTACKS RENDER EMPLOYEE UNQUALIFIED UNDER
ADA

A former customer service worker for a Wisconsin power
company fired after having panic attacks at work that likely
stemmed from a head injury was unable to establish that her
discharge was illegal under the Americans with Disabilities
Act, the Seventh Circuit rules ("Emerson v. Northern States
Power Co.,  "7th Cir.,  No. 00-3746,  6/26/01).

Loretta M. Emerson failed to show she was a "qualified
individual" under the act, given that her anxiety attacks
could interfere with her ability to answer customer phone
calls about gas or electricity emergencies, Judge Bauer
finds, affirming summary judgment to Northern States Power
Co. Bauer also finds Emerson posed a direct threat to her
employer, because her job "required prompt, accurate
handling of emergencies such as gas leaks and downed power
lines that could pose significant danger to the public." . .
. Page A-8

http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5q2p6_


UAN DELEGATES VOTE UNANIMOUSLY TO AFFILIATE WITH AFL-CIO

Delegates to the National Labor Assembly of the United
American Nurses, the labor arm of the American Nurses
Association, unanimously vote to affiliate with the AFL-CIO.
If all goes as planned, the affiliation of the
100,000-member union will become effective July 1. However,
it appears one more hurdle may need to be cleared before the
affiliation, which has been in the works for more than a
year, becomes a reality.

The ANA House of Delegates is scheduled to vote June 30 on a
bylaw change that would require any state nurses'
association that engages in collective bargaining to be a
member of UAN within four years. This was a condition of the
AFL-CIO granting a charter. It is unclear whether the bylaw
change will pass, and if it does not what happens to the
affiliation agreement. . . . Page B-1

http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5j7f6_


NEW YORK CITY PARTLY IMMUNE FROM BIAS LAW, COURT FINDS

In a case of first impression, a federal trial court
overturns a jury's $1 million sexual harassment punitive
damages award against New York City because it did not
explicitly waive sovereign immunity from punitive damages
under the city's human rights ordinance ("Katt v. New York
City, "S.D.N.Y., No. 95 Civ. 8283 (GEL), 6/19/01). Rejecting
the defendants' other post-verdict motions, however, Judge
Lynch of the U.S. District Court for the Southern District
of New York upholds the jury's award of $400,000 in
compensatory damages.

The court rejects the city's affirmative defense that
plaintiff Alli Katt failed to take advantage of the New York
Police Department's complaint process, finding that she was
intimidated into not doing so because of explicit and
implicit pressure. The court also rejects the city's
late-raised challenge to the timeliness of the complaint. .
. . Page A-1

http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j4v7g9_


HOFFA, LEEDHAM NOMINATED AS CANDIDATES FOR TEAMSTERS
PRESIDENT

In a noisy but orderly session of the International
Brotherhood of Teamsters convention June 28, incumbent
President James P. Hoffa and challenger Tom Leedham both are
nominated for the union's top office.  Also nominated are
current IBT Secretary-Treasurer Tom Keegel and Leedham
running-mate Tom Gilmartin, the head of IBT Local 559 in
Connecticut. Delegate voting will occur late June 28 to
determine if the candidates received the requisite 5 percent
support for their names to be placed on the ballot for the
fall election among the union's 1.4 million members.

That Hoffa will receive 5 percent of the delegates' votes is
a foregone conclusion given his overwhelming support among
the more than 1,700 delegates. Voice votes on various
resolutions and constitutional amendments appear to show
that Leedham has the support of only a few hundred delegates
in his second challenge to Hoffa for the union presidency.
However, Leedham and members of his campaign appear
confident he will get the votes necessary to be placed on
the ballot. Other members of Leedham's slate earlier
received more votes than necessary to be placed on the
ballot. . . . Page C-1

http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5g8z1_


OSHA READIES MANDATORY EMPLOYER SURVEY FOR DISTRIBUTION

The week of July 2 will signal the launch of the
Occupational Safety and Health Administration's annual
mandatory survey of more than 80,000 employers nationwide to
gather injury and illness data to better target high-hazard
employers. The agency, however, will not include
construction employers in the upcoming survey.

The 2001 survey program "improves OSHA's ability to identify
and target our  efforts on the more hazardous workplaces,"
acting OSHA Administrator R. Davis Layne says. The survey
requests calendar year 2000 data. OSHA inspections based on
the 2000 data will not be launched until January or February
of 2002, the OSHA spokesman says.

Employers will be asked to supply figures for average
employment, hours worked, and a summary of the job-related
injuries and illnesses that occurred at their work sites in
2000, the agency says.  The surveys must be returned even if
a surveyed employer recorded no occupational injuries or
illnesses for 2000, the agency says. . . . Page A-1

http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5h0x6_


______________

TODAY'S EVENTS
______________

GDP: Second revision of gross domestic product for the first
quarter released, 8:30 a.m., Commerce Department.

________________

ALSO IN THE NEWS
________________


LAYOFFS: Reflecting the weakened labor market, both the
number of mass layoff events and the number of workers
involved were significantly higher during the first five
months of this year than in the same period of 2000. The
layoff events reported for May alone involved a total of
155,759 workers. . . . Page D-1

http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5j8p4_

UNEMPLOYMENT INSURANCE: New UI claims filed with state
agencies fell for the third consecutive week, down 16,000 to
a seasonally adjusted total of 388,000 for the week ended
June 23. . . . Page D-6

http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5h5h2_

HEALTH CARE EMPLOYEES: Several factors are combining to
constrain the current supply of nurses in the United States,
a key factor being job dissatisfaction, according to the
General Accounting Office. . . . Page A-5

http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5c8p3_

ENTERTAINMENT: Members of six unions representing 25,000
workers at Walt Disney World in Orlando, Fla., are scheduled
to vote July 6 on a new three-year contract with the Walt
Disney World Co. . . . Page A-6

http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5m9f3_


____

TEXT
____

UNFAIR LABOR PRACTICES: District of Columbia Circuit
decision in "Adtranz ABB Daimler-Benz Transportation N.A.
Inc. v. NLRB. ". . . Page E-1

http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5e3e4_


_________________

TABLE OF CONTENTS
_________________

LEADING THE NEWS

UNFAIR LABOR PRACTICES
   Overturning NLRB, D.C. Circuit finds California firm's
   workplace policies barring abusive and threatening
   language and restricting solicitation and distribution
   did not constitute unfair labor practices . . . Page
   AA-1,  Text E-1
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5k3h4_

   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5e3e4_


____

NEWS
____

DISABILITIES
   Seventh Circuit rules former customer service worker at
   Wisconsin power company, fired after having panic attacks
   at work likely related to head injury, failed to
   establish she was "qualified individual" under ADA . . .
   Page A-8
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5q2p6_

DISCRIMINATION
   House Judiciary Committee expects to vote on bill (H.R.
   7) that would allow religious organizations to compete
   for federal grants, including proposed amendment from
   panel chairman that would narrow ability of such
   organizations to discriminate in employment . . . Page
   A-12
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5m7q5_

ECONOMIC OUTLOOK
   UCLA Anderson Forecast finds California facing most
   troublesome period since early 1990s, predicts sharply
   lower growth through at least 2002 . . . Page A-3
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j4m8v2_

ENTERTAINMENT
   Members of six unions representing 25,000 workers to vote
   July 6 on new three-year contract with Walt Disney World
   Co. . . . Page A-6
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5m9f3_

HEALTH CARE
   Senate Democrats prevail on amendment challenges to
   patients' bill of rights legislation, but prospects for
   wrapping up work on bill by close of Senate business for
   night appear dim . . . Page A-10
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5v0u5_

HEALTH CARE EMPLOYEES
   GAO cites job dissatisfaction as top among several
   factors combining to constrain current supply of nurses
   in United States . . . Page A-5
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5c8p3_

HELP-WANTED ADS
   Conference Board finds demand for labor declined in May
   as help-wanted advertising index fell by 5 percentage
   points from previous month, to 60 percent . . . Page A-5
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5j9t7_

SAFETY & HEALTH
   Official says Labor Department will go forward with
   Clinton administration rule changing the way some 1.3
   million worksites are required to record employee
   injuries and illnesses . . . Page A-9
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5r0g7_

   OSHA announces July 2 launch of annual mandatory survey
   gathering injury and illness data from more than 80,000
   employers to better target high-hazard employers . . .
   Page A-1
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5h0x6_

   Study finds consequences of feeling overworked can affect
   employees' job performance and lead to poorer health . .
   . Page A-6
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5n9r1_

SEX DISCRIMINATION
   Seventh Circuit affirms grant of summary judgment to
   employer of female manager passed over for promotion and
   transferred to another facility, finding that she failed
   to establish similarly situated male was treated more
   favorably . . . Page A-4
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j4g0q8_

SEXUAL HARASSMENT
   Federal judge overturns jury's award of $1 million in
   punitive damages against New York City because city did
   not explicitly waive sovereign immunity under human
   rights ordinance . . . Page A-1
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j4v7g9_

STEEL
   Geneva Steel and United Steelworkers reach tentative,
   one-year contract covering 1,500 workers at company's
   Vineyard, Utah, mill . . . Page A-13
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5g8h7_

TRADE
   In letter to President Bush, twenty-five House Democrats
   denounce direction House GOP leadership and
   administration are taking on trade . . . Page A-7
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5q2j2_

WORKFORCE REDUCTIONS
   John Deere & Co. announces plans to cut salaried
   workforce in United States by 8 percent, or 1,250 jobs .
   . . Page A-13
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5d1v8_


______________

SPECIAL REPORT
______________

HEALTH CARE EMPLOYEES
   Delegates to second annual National Labor Assembly of
   United American Nurses, labor arm of American Nurses
   Association, vote unanimously to affiliate with AFL-CIO .
   . . Page B-1
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5j7f6_


_________________

CONVENTION REPORT
_________________

TEAMSTERS
   IBT delegates nominate incumbent President James P. Hoffa
   and challenger Tom Leedham for union's top office in
   noisy but orderly session . . . Page C-1
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5g8z1_


_____________

ECONOMIC NEWS
_____________

LAYOFFS
   Labor Department's Bureau of Labor Statistics reports
   both number of mass layoff events and number of workers
   involved were significantly higher during first five
   months of this year than during same period last year,
   reflecting weakened labor market . . . Page D-1
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5j8p4_

UNEMPLOYMENT INSURANCE
   Labor Department's Employment and Training Administration
   reports new unemployment insurance claims filed with
   state agencies fell for third consecutive week, down
   16,000 to seasonally adjusted total of 388,000 for week
   ended June 23 . . . Page D-6
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5h5h2_


____

TEXT
____

UNFAIR LABOR PRACTICES
   District of Columbia Circuit decision in "Adtranz ABB
   Daimler-Benz Transportation N.A. Inc. v. NLRB" . . . Page
   E-1
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5e3e4_


______________

TABLE OF CASES
______________

Adtranz ABB Daimler-Benz Transp. N.A. Inc. v. NLRB (D.C.
Cir.) . . . Page AA-1,  text E-1
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5k3h4_

   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5e3e4_

Emerson v. Northern States Power Co. (7th Cir.) . . . Page
A-8
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j5q2p6_

Hoffman-Dombrowski v. Arlington Int'l Racecourse Inc. (7th
Cir.) . . . Page A-4
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j4g0q8_

Katt v. New York City (S.D.N.Y.) . . . Page A-1
   http://pubs.bna.com/ip/BNA/dlr.nsf/id/a0a4j4v7g9_

   __________
   Daily Labor Report (ISSN 1522-5968) Highlights are
   published daily by The Bureau of National Affairs, Inc.,
   1231 25th St., NW, Washington, DC 20037.

   For account information and changes, contact
   1-800-372-1033 (M-F, 8:30 am-7:00 pm ET)

   To request retransmission or to order a copy of the
   summarized article, contact 1-800-452-7773 or e-mail
   bnaplus@bna.com.

   For copyright guidelines, go to
   http://www.bna.com/corp/copyright.

   Copyright (c) 2001 by The Bureau of National Affairs,
   Inc.  Washington, D.C.  20037.  Use of this service is
   subject to the terms and conditions of the license
   agreement with BNA.  Unauthorized access or distribution
   is prohibited.

In [57]:
# We would first combine these df
df = pd.concat([df1,df2,df3],axis = 0, ignore_index = True)
df.head()

                                               Email  Label
0  User ID:  enrondlr\nPW:        bnaweb22\n\n\n ...      1
1  \nHi Chris,  \n\nTonight we are rolling out a ...      1
2  Rika r these new?\n\n -----Original Message---...      1
3  John/Gerald,\n\nWe are currently trading under...      1
4  Gerald and Stacy -\n\nAttached is a worksheet ...      1

In [58]:
# For whatever we use
print("Total: ", df.shape[0])
print("Ham: ", np.sum(df["Label"]))
print("Spam: ", df.shape[0] -  np.sum(df["Label"]))

Total:  131578
Ham:  73551
Spam:  58027

In [46]:
#We found that there is non-
print(df["Email"][61554])

nan

In [60]:
def remove_html(text):
    html_pattern = re.compile('<.*?>')
    return html_pattern.sub(r'', text)


df["Email"] = df["Email"].apply(lambda x : remove_html(x))

In [61]:
#Lowercasting
df["Email"] = df["Email"].str.lower()

In [62]:
df.head()

                                               Email  Label
0  user id:  enrondlr\npw:        bnaweb22\n\n\n ...      1
1  \nhi chris,  \n\ntonight we are rolling out a ...      1
2  rika r these new?\n\n -----original message---...      1
3  john/gerald,\n\nwe are currently trading under...      1
4  gerald and stacy -\n\nattached is a worksheet ...      1

In [64]:
#Remove urls
import re
def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)


df["Email"] = df["Email"].apply(lambda text: remove_urls(text))
df.head()

                                               Email  Label
0  user id:  enrondlr\npw:        bnaweb22\n\n\n ...      1
1  \nhi chris,  \n\ntonight we are rolling out a ...      1
2  rika r these new?\n\n -----original message---...      1
3  john/gerald,\n\nwe are currently trading under...      1
4  gerald and stacy -\n\nattached is a worksheet ...      1

In [66]:
#Punctual removal
import string
PUNCT_TO_REMOVE = string.punctuation
def remove_punctuation(text):
    """custom function to remove the punctuation"""
    return text.translate(str.maketrans('', '', PUNCT_TO_REMOVE))

df["Email"] = df["Email"].apply(lambda x : remove_punctuation(x))
print(df["Email"][1])

hi chris

tonight we are rolling out a new report  currently only you and jon have access to it  youll select it off the main reports menu  it will say ngx download report  when you launch it it will show the data on screen like all other reports  there is a button at the bottom that says export  clicking it will give you several selections  choose the one that says save to ngx xml  you can then save it as a file which can be mailed to ngx

let me know if there is anyone else who needs access

thanks
 jay

In [67]:
import nltk
from nltk.corpus import stopwords

#nltk.download('stopwords')
STOPWORDS = set(stopwords.words('english'))
def remove_stopwords(text):
    """custom function to remove the stopwords"""
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])


df["Email"] = df["Email"].apply(lambda x : remove_stopwords(x))
print("Execuated")

Execuated

In [68]:
#Lemmatiaztion
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
lemmatizer = WordNetLemmatizer()
def lemmatize_words(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

df["Email"] = df["Email"].apply(lambda text: lemmatize_words(text))

[nltk_data] Downloading package wordnet to /home/yau/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [71]:
print(df["Email"][1])

hi chris tonight rolling new report currently jon access youll select main report menu say ngx download report launch show data screen like report button bottom say export clicking give several selection choose one say save ngx xml save file mailed ngx let know anyone else need access thanks jay

In [72]:
df.to_csv(f"{os.getcwd()}/Processed_Read", index = False)

The following code is not used!!!!!!!!!!!!!
Please don't click the following!!!!!!!!!

In [10]:
#We could also do removal of frequent and rare word but not sure if useful
# More safe to Lemmatization so we would not run this code
#Stemming

from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()
def stem_words(text):
    return " ".join([stemmer.stem(word) for word in text.split()])

df["Email"] = df["Email"].apply(lambda text: stem_words(text))
df.head()

                                               Email  Label
0  receiv nahoumsmbx01v 19216811039 nahoumsmbx05v...      1
1  receiv nahoumsmbx03vcorpenroncom 19216811040 n...      1
2  receiv nahoumsmbx01v 19216811039 nahoumsmbx05v...      1
3  receiv nahoumsmbx01v 19216811039 nahoumsmbx05v...      1
4  receiv nahoumsmbx03vcorpenroncom 19216811040 n...      1

In [11]:
#Removal of the \n \t we shall remove this before removing Punctual(if applicable)
#Not sure if useful!!!!!!
def remove_escape_sequences(text):
    replacements = {"\\n": "", "\\t": "", "\\b": ""}
    for escape, replacement in replacements.items():
        text = text.replace(escape, replacement)
    return text
#ESCAPE_SEQUENCE = {"\n","\t","\b"}

df["Email"] = df["Email"].apply(lambda x : remove_escape_sequences(x))

AttributeError: 'float' object has no attribute 'replace'

In [21]:
#Remove those byte stuff
# Don't execuate for read one
df["Email"]= df["Email"].apply(lambda x:x[2:-1])